# Generated by Django 4.2 on 2025-07-27 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'interest_group',
            },
        ),
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30, unique=True)),
                ('interest_group_id', models.ForeignKey(db_column='interest_group_id', on_delete=django.db.models.deletion.CASCADE, to='personal.interestgroup')),
            ],
            options={
                'db_table': 'interest_tag',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_column='nickname', max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='gender', max_length=1)),
                ('birthday', models.DateField(blank=True, db_column='birthday', null=True)),
                ('bio', models.TextField(blank=True, db_column='bio', default='', max_length=500)),
                ('preferred_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='preferred_gender', max_length=1, null=True)),
                ('preferred_age_min', models.PositiveIntegerField(db_column='preferred_age_min', default=18)),
                ('preferred_age_max', models.PositiveIntegerField(db_column='preferred_age_max', default=40)),
                ('preferred_distance_km', models.PositiveIntegerField(db_column='preferred_distance_km', default=30)),
                ('cdatetime', models.DateTimeField(auto_now_add=True, db_column='cdatetime')),
                ('mdatetime', models.DateTimeField(auto_now=True, db_column='mdatetime')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_column='image', upload_to='profile_photos/')),
                ('cdatetime', models.DateTimeField(auto_now_add=True, db_column='cdatetime')),
                ('mdatetime', models.DateTimeField(auto_now=True, db_column='mdatetime')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='personal.profile')),
            ],
            options={
                'db_table': 'profile_photo',
            },
        ),
        migrations.CreateModel(
            name='ProfileInterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_tag', models.ForeignKey(db_column='interest_tag_id', on_delete=django.db.models.deletion.CASCADE, to='personal.interesttag')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='personal.profile')),
            ],
            options={
                'db_table': 'profile_interest_tag',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='profiles', through='personal.ProfileInterestTag', to='personal.interesttag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profilephoto',
            index=models.Index(fields=['profile'], name='idx_photo_profile'),
        ),
        migrations.AlterUniqueTogether(
            name='profileinteresttag',
            unique_together={('profile', 'interest_tag')},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='idx_profile_gender'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['preferred_gender'], name='idx_prefer_gender'),
        ),
        migrations.AlterUniqueTogether(
            name='interesttag',
            unique_together={('interest_group_id', 'name')},
        ),
    ]
