# Generated by Django 4.2 on 2025-07-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_init', models.BooleanField(db_column='is_init', default=False)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='init', to='personal.profile')),
            ],
        ),
    ]
