# Generated by Django 4.2 on 2025-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_profileinit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='gender', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', through='personal.ProfileInterestTag', to='personal.interesttag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, db_column='nickname', max_length=30, null=True),
        ),
    ]
