# Generated by Django 4.2 on 2025-07-31 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_profile_gender_alter_profile_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, db_column='status', max_length=20, null=True)),
                ('cdatetime', models.DateTimeField(auto_now_add=True, db_column='cdatetime')),
                ('mdatetime', models.DateTimeField(auto_now=True, db_column='mdatetime')),
                ('matchtime', models.DateTimeField(blank=True, db_column='match_time', null=True)),
                ('lifttime', models.DateTimeField(blank=True, db_column='lifttime', null=True)),
                ('profile1', models.ForeignKey(db_column='profile_1', on_delete=django.db.models.deletion.CASCADE, related_name='match_profile_1', to='personal.profile')),
                ('profile2', models.ForeignKey(db_column='profile_2', on_delete=django.db.models.deletion.CASCADE, related_name='match_profile_2', to='personal.profile')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.DeleteModel(
            name='ProfileInit',
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('profile1', 'profile2'), name='unique_match_profiles'),
        ),
    ]
